import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './components/Header/Header'
import Modal from './components/Modal/Modal'
import ClientOnly from './components/ClientOnly'
import RegisterModal from './components/Modal/RegisterModal'
import ToasterProvider from './providers/ToastProvider'
import LoginModal from './components/Modal/LoginModal'
import  getCurrentUser  from './actions/getCurrentUser'
import RentModal from './components/Modal/RentModal'
import SearchModal from './components/Modal/SearchModal'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurrentUser()
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ToasterProvider />
        <RentModal />
        <LoginModal />
        <RegisterModal />
        <SearchModal/>
        <Header currentUser={currentUser} />
        <div className='pb-20 pt-28'>{children}</div>
      </body>
    </html>
  )
}
